### ISSUE TITLE
ping

### ISSUE THREAD

**Issue by kamakshidasan** [Pseudomanifold/Aleph#52]
submanifold was a cool github identifier.

**Comment by Pseudomanifold** [comment]
Thanks! Not sure how I can solve that issue, though ;)

**Comment by kamakshidasan** [comment]
Well, change back! A lot of your older links now seem to be broken -
including the ones hardcoded in your papers.

**Comment by Pseudomanifold** [comment]
Most of the redirects should be done automatically. I rather want to keep the new username for consistency reasons (my Twitter handle is the same). Could you point me towards some of the redirects that do _not_ work? Then I can try to fix those.

**Comment by kamakshidasan** [comment]
I checked the links which failed last time around - they seem to working now. :)

Also, I really like few of your papers: clique community persistence and interlevel set hierarchy.

**Comment by Pseudomanifold** [comment]
Thanks! Let me know if you want to discuss those or anything research-related :)

**Comment by kamakshidasan** [comment]
https://submanifold.github.io/Aleph/Rieck17d.html
https://submanifold.github.io/Aleph/Rieck17b.html
https://submanifold.github.io/Aleph/Rieck17a.html
https://submanifold.github.io/Aleph/Rieck16b.html
https://submanifold.github.io/Aleph/Rieck17d.html
https://submanifold.github.io/Aleph/Rieck17b.html
https://submanifold.github.io/Aleph/Rieck17a.html
https://submanifold.github.io/Aleph/Rieck16b.html

These do not seem to redirect

**Comment by Pseudomanifold** [comment]
Thanks, I updated and fixed all of the links now.
