### ISSUE TITLE
Not able to build due to error in test_spine.cc.o 

### ISSUE THREAD

**Issue by chaxor** [Pseudomanifold/Aleph#54]
Building from source from github is not working due to the error below:

    make[2]: *** [tests/CMakeFiles/test_spine.dir/build.make:63: tests/CMakeFiles/test_spine.dir/test_spine.cc.o] Error 1

I have verified this on 3 different machines, using the standard `make` commands after cloning with git, or using the provided PKGBUILD / `yay` / packer / pacaur, etc.

**Comment by Pseudomanifold** [comment]
Could you add more lines of the error output? I need more information to be able to debug this. As workaround, you could disable this test or build with `make -k^, which ignores all errors.

**Comment by Pseudomanifold** [comment]
I have fixed some issues with `test_spine` that arose from problems with the combinatorics module. Please re-open the issue if the problem persists.
